- src/dsl/ContextMaps.jl
- src/dsl/Parsing.jl
- src/dsl/TheoryMacros.jl
- test/logic/ContextMaps.jl
- test/stdlib/tests.jl
My attempt to resolve #4.
So we can use `a,b,c::T` to denote the context `a::T,b::T,c::T`.
> Allow omitting repetitive type annotations.

- docs/make.jl
- docs/src/api.md
- docs/src/stdlib.md
This PR adds the submodules to the API docs. @olynch, there are no docs generated for the stdlib. But I think we should have a central page for that.
> DOCS: Add modules to api reference

- Project.toml
- src/stdlib/Serialization.jl
- src/stdlib/models/SimpleLenses.jl
- src/stdlib/module.jl
- src/syntax/Theories.jl
- src/util/Names.jl
- test/Project.toml
- test/stdlib/Serialization.jl
- test/stdlib/tests.jl
This also adds serialization for everything AlgebraicLenses depends on. However, this approach to serialization is perhaps not as general as I might like; it will do for the demo though.
> Serialization for Algebraic Lenses

- src/syntax/Presentations.jl
- test/syntax/Presentations.jl
Ignore LineNumberNodes when parsing presentation. Addresses https://github.com/AlgebraicJulia/GATlab.jl/issues/94
> fix presentation parser

- src/stdlib/models/GATs.jl
- src/stdlib/models/module.jl
- src/stdlib/module.jl
- src/stdlib/theories/Algebra.jl
- src/stdlib/theories/Naturals.jl
- src/stdlib/theorymaps/Maps.jl
- src/stdlib/theorymaps/module.jl
- src/syntax/ExprInterop.jl
- src/syntax/GATs.jl
- src/syntax/Scopes.jl
- src/syntax/TheoryMaps.jl
- src/syntax/module.jl
- test/stdlib/models/GATs.jl
- test/stdlib/models/tests.jl
- test/syntax/GATs.jl
- test/syntax/Scopes.jl
- test/syntax/TheoryMaps.jl
- test/syntax/tests.jl
Some initial work for theory morphism support.
The key features now are `@theorymap` macro, the pushing forward of terms along theory morphisms and the model `GATC` (for `ThCategory`) of GATs and GAT morphisms.  Additionally the `stdlib` now has a file for standard theory morphisms, such as `swap: ThMonoid -> ThMonoid`, interpreting preorders as categories and interpreting the naturals + addition as a monoid. 
Pushing forward terms required a new struct `TermInCtx` for AlgTerms in a TypeScope as well as an implementation of type inference (`TermInCtx -> AlgType`).
> Theory Morphisms

- src/models/ModelInterface.jl
- src/stdlib/models/FinMatrices.jl
- src/stdlib/models/FinSets.jl
- src/stdlib/models/GATs.jl
- src/stdlib/models/Nothings.jl
- src/stdlib/models/SliceCategories.jl
- src/syntax/TheoryInterface.jl
- test/models/ModelInterface.jl
Keyword arguments don't play well with dispatch, and we don't want the model to be the first parameter when unwrapped by `WithModel` because models might be elements of another model, so instead we pass in the model via stuff like `id[FinSetC()](3)`.
> Pass model via Base.getindex

- src/stdlib/models/FinSets.jl
- src/stdlib/models/Op.jl
- src/stdlib/models/module.jl
- test/stdlib/models/FinSets.jl
- test/stdlib/models/Op.jl
- test/stdlib/models/tests.jl
An `OpC` model is a struct that wraps a category. Some tests of `op(FinSetC)` are provided.
Addresses https://github.com/AlgebraicJulia/GATlab.jl/issues/101
> opposite category model in stdlib

- src/models/ModelInterface.jl
- src/stdlib/models/Arithmetic.jl
- src/stdlib/models/module.jl
- src/stdlib/theories/Naturals.jl
- src/syntax/GATs.jl
- src/syntax/TheoryInterface.jl
- test/stdlib/models/Arithmetic.jl
- test/stdlib/models/tests.jl
This allows us to explicitly declare that the generated methods in the associated theory module extend some other methods.
> add import statements to @theory declaration

- src/stdlib/theorymaps/Maps.jl
- src/syntax/GATs.jl
- src/syntax/Scopes.jl
- src/syntax/TheoryMaps.jl
- test/syntax/GATs.jl
- test/syntax/TheoryMaps.jl
This removes an earlier restriction that sent AlgSorts to AlgSorts. 
This allows us to express the theory morphism `op: ThCategory -> ThCategory`.
> Theory maps send type constructors to general types in a context

- src/models/SymbolicModels.jl
- src/stdlib/models/module.jl
- src/stdlib/module.jl
- src/stdlib/theorymaps/Maps.jl
- src/syntax/GATs.jl
- src/syntax/Presentations.jl
- src/syntax/Scopes.jl
- src/syntax/TheoryMaps.jl
- src/syntax/module.jl
- test/stdlib/models/GATs.jl
- test/stdlib/models/tests.jl
- test/syntax/GATs.jl
- test/syntax/Presentations.jl
- test/syntax/Scopes.jl
- test/syntax/TheoryMaps.jl
- test/syntax/tests.jl
TermInCtx and TypeInCtx are made more flexible to take a general context, rather than just a scope. This required making Context take {T, Sig} type parameters.
Previously we had conflicting meanings of `idents` - one was for broadcasting arguments to `ident` and the other was listing all the idents in a Context. The latter is now called `getidents`.
Also theory maps before required some redundancy in the expressions they parsed, this has been improved so that we can write `compose(f,g) ⊣ [(a,b,c)::Ob,f::Hom(a,b), g::Hom(b,c)] => compose(g, f)` with no explicit RHS context.
> TypeCtx as generalization of TypeScope, better @theorymap parsing

- src/stdlib/theories/Algebra.jl
- src/stdlib/theories/Categories.jl
- src/stdlib/theories/Naturals.jl
- src/syntax/GATs.jl
For compat with Catlab, we now can infer the type of an axiom declaration rather than requiring it to be manually specified.
Reminder that in general type inference can be ambiguous modulo the equations of a GAT - in the future we'll use E-graphs for this inference.
> infer axiom type + improved normalize_decl

- src/models/Presentations.jl
- src/models/SymbolicModels.jl
Just like how the module created by `@theory` now has a `Meta` submodule, so does the module created by `@symbolic_module`.
> Meta module inside symbolic model module

- Project.toml
Need to remove spurious catlab dependency
> Remove Catlab dependency

- src/syntax/gats/gat.jl
Addresses a warning that GATlab is currently emitting. (https://github.com/AlgebraicJulia/GATlab.jl/issues/124)
> Fix precompilation warning about unordered dicts

- .codecov.yml
The build has been failing for a while now because we're slightly under 95%.
> Reduce code coverage target to 90%

- Project.toml
- src/syntax/GATs.jl
Now that ACSets.jl exports `equations`, and Catlab inherits from both ACSets and GATlab, I have added `equations` to AlgebraicInteraces so that both ACSets and GATlab can extend the same function. This PR also bumps the version number so that we can cut a new minor release before integrating with Catlab.
> Import equations from AlgebraicInterfaces and bump version

- Project.toml
- src/syntax/Scopes.jl
Now that `getvalue` is also used in ACSets.jl, we need to import this method from AlgebraicInterfaces so that downstream packages like Catlab can use `getvalue` without it being ambiguous.
> Use `getvalue` from AlgebraicInterfaces

- src/syntax/TheoryInterface.jl
- test/syntax/TheoryInterface.jl
Due to an external change, the result of `@doc` inside the `@theory` macro returns a `Base.Docs.DocStr` object rather than a `Markdown.MD` object. This broke some tests. This PR offers a partial fix. It is partial because the docstring one puts above `@theory` was copied in two places before: both the module and the GAT were given the same docstring before. However, I wasn't able to figure out how to get the fix to work for the GAT, though we do recover the same docstring as before at the module level.
Thus `@doc ThCategory` will work the same as before, but there is a regression insofar as `ThCategory.Meta.theory` will not have documentation. (Hence, two lines are commented out in the tests now)
> Fix docstring error

- src/models/ModelInterface.jl
- src/syntax/TheoryInterface.jl
- test/models/ModelInterface.jl
- test/syntax/TheoryInterface.jl
Addresses https://github.com/AlgebraicJulia/GATlab.jl/issues/167
This changes what `@import` does within the `@instance` macro. Rather than removing expected signatures, whenever we have leftover unimplemented signatures we check if the name of the method is in the imports and ignore the missing method error if so.
I've tested that this doesn't break Catlab.
> Fix logic of `@import`

- src/models/ModelInterface.jl
- test/Project.toml
- test/models/ModelInterface.jl
Addresses https://github.com/AlgebraicJulia/GATlab.jl/issues/169
> Allow WithModel dispatch to accept subtypes

- src/models/ModelInterface.jl
- src/nonstdlib/models/Pushouts.jl
- src/stdlib/derivedmodels/DerivedModels.jl
- src/stdlib/models/arithmetic.jl
- src/stdlib/models/finmatrices.jl
- src/stdlib/models/finsets.jl
- src/stdlib/models/gats.jl
- src/stdlib/models/nothings.jl
- src/stdlib/models/op.jl
- src/stdlib/models/slicecategories.jl
- src/syntax/GATs.jl
- src/syntax/TheoryInterface.jl
- src/syntax/TheoryMaps.jl
- src/syntax/gats/gat.jl
- test/models/ModelInterface.jl
- test/stdlib/FinMatrices.jl
- test/stdlib/FinSets.jl
- test/stdlib/Nothings.jl
- test/stdlib/Op.jl
- test/stdlib/SliceCategories.jl
Addresses https://github.com/AlgebraicJulia/GATlab.jl/issues/174
This fixes the typo of the catch-all case, i.e. 
```julia
implements(m::Module,::Type{Val{tag}}) where tag = nothing
``` 
We replace `Module` with `Any`. 
However, the way we check whether or not an `@instance` call needs to define a new instance method is whether or not there are *any* methods `implements(::ModelType, Val{specific_tag})`. So now there is one that is always there by default. 
One would think, then, that the correct way to fix this logic is to check whether or not there is exactly *one* method, rather than zero like before. However, because of how `methods` works, once some earlier `@instance` call has already defined the more specific `implements` method (which returns not `nothing`), it's not that there are …
> Allow checking if a model does NOT implement a given theory

- src/models/ModelInterface.jl
- src/models/SymbolicModels.jl
- src/nonstdlib/module.jl
- src/stdlib/theories/algebra.jl
- src/syntax/Scopes.jl
- src/syntax/TheoryInterface.jl
- src/syntax/TheoryMaps.jl
- src/syntax/gats/gat.jl
- test/models/ModelInterface.jl
- test/models/SymbolicModels.jl
This addresses https://github.com/AlgebraicJulia/GATlab.jl/issues/178
One can declare that `Foo` is a single-field struct which wraps models of `ThCategory` via `ThCategory.Meta.@wrapper Foo`. This type can be a subtype of an abstract type too: `ThCategory.Meta.@wrapper Foo <: MyAbsType`.
We may also want to generate a wrapper struct which has type parameters for the associated Julia types, so `ThCategory.Meta.@typed_wrapper Foo` means that `Foo(FinCatC()) isa Foo{Int,Vector{Int}}`
It's unclear if we should just have the typed version and, if one doesn't need to use the type parameters, one can ignore them.
> Wrapper struct for models of a theory

- src/GATlab.jl
- test/models/ModelInterface.jl
- test/models/Presentations.jl
- test/models/SymbolicModels.jl
- test/nonstdlib/Pushouts.jl
- test/stdlib/Arithmetic.jl
- test/stdlib/FinMatrices.jl
- test/stdlib/FinSets.jl
- test/stdlib/GATs.jl
- test/stdlib/Nothings.jl
- test/stdlib/Op.jl
- test/stdlib/SliceCategories.jl
- test/syntax/GATContexts.jl
- test/syntax/GATs.jl
- test/syntax/TheoryMaps.jl
GATlab standard library should be opt-in rather than exported by default, as it's often the case that important names (e.g. `FinSetC`, `op`) are claimed which might require alternative / more serious implementations elsewhere, such as Catlab.
> Don't reexport StdLib

- src/models/ModelInterface.jl
- src/stdlib/models/arithmetic.jl
- src/stdlib/models/finmatrices.jl
- src/stdlib/models/finsets.jl
- src/stdlib/models/slicecategories.jl
- test/models/ModelInterface.jl
- test/stdlib/Arithmetic.jl
- test/stdlib/FinMatrices.jl
- test/stdlib/FinSets.jl
- test/stdlib/Op.jl
- test/stdlib/SliceCategories.jl
This is a partial step towards moving away from static typechecking of instances (we will be dynamically checking whether a model implements a theory in the future). The `@fail` macro was supposed to be helpful way to make getting the context of an error in the validation methods (overloads of the names of type constructors). It required some macro + closure trickery that's ultimately too difficult to maintain while making other required changes to GATlab for the Catlab refactor.
> Remove `@fail`

- docs/src/concepts/models.md
- src/models/ModelInterface.jl
- src/models/SpecialModels.jl
- src/models/SymbolicModels.jl
- src/models/module.jl
- src/nonstdlib/models/Pushouts.jl
- src/stdlib/models/op.jl
- src/stdlib/models/slicecategories.jl
- src/syntax/TheoryInterface.jl
- src/util/Eithers.jl
- src/util/MetaUtils.jl
- test/models/ModelInterface.jl
- test/models/SpecialModels.jl
- test/models/SymbolicModels.jl
- test/models/tests.jl
This PR changes how GATlab tracks whether a model implements a theory. It removes the static typechecking which was often too underpowered to handle things which were morally correct. 
Before we had `implements` methods generated during `@instance` for each model type + scopetag. it would return some documentation if, e.g., `FinSetC` implements `compose` and otherwise a `MethodError` would be thrown as the method doesn't exist. In this new approach, an `impl_type(::FinSetC, x::Ident)` method gets generated which ....
This removes the need for `@import` when defining an extension of a model. 
This PR also adds special models (Dispatch, Initial, Terminal) which can be made sense of in any theory.
> Runtime checking for whether a model implements a theory, special distinguished models for each theory

- src/models/ModelInterface.jl
- src/models/SymbolicModels.jl
- src/syntax/TheoryInterface.jl
This *undoes* a change made earlier in this series of PRs where the code which generated alias was methods was changed. The change was to allow us to define just once 
```julia 
ThCategory2.*(anymodel::WithModel, xs...) = ThCategory2.composeH(anymodel, xs...)
```
whenever, e.g., `ThCategory2` is defined, rather than handling aliases for every single theory + model combination in the `@instance` code.
The issue only revealed itself towards the end of the Catlab refactor, when it became clear two different theories (`ThCategory2` and `ThCopresheaf`) both `import` the same symbol, `Base.:*` and made them aliases for *differently named* things (`composeH` and `act`, respectively). This means when the second theory is defined, we emit the code  
```julia 
ThCopresheaf.*(anymodel::WithModel, …
```
> Define alias methods in `@instance` rather than `@theory`

- src/models/ModelInterface.jl
- src/syntax/TheoryInterface.jl
- test/models/ModelInterface.jl
Addresses https://github.com/AlgebraicJulia/GATlab.jl/issues/192
> Named instance type assignments

- src/syntax/TheoryInterface.jl
- test/models/SpecialModels.jl
Dispatch models are special models that have the meaning of "just use dispatch". Previously one could index a method with a dispatch model, i.e. `f[d](args...) = f(args...)`. However to be more consistent with normal models, we also need a `f(::WithModel{Dispatch}, args...) = f(args...)` method to be automatically generated for each theory operation.
> Allow WithModel with Dispatch models

- src/stdlib/models/op.jl
- src/syntax/TheoryInterface.jl
- test/stdlib/Op.jl
Opposite cat models have a piece of data: something which implements `ThCategory` itself. This is a great use case for wrapper types around models, so this PR shows how to use wrapper types in this context (removing the need to manually check that that the value implements `ThCategory`).
This also forces us to not rely on `GATlab` being in the namespace of wherever `@wrapper` gets expanded. The solution is to use `GlobalRef`.
> Use a wrapper type for ThCategory in Opposite cat models

- src/models/ModelInterface.jl
- src/syntax/TheoryInterface.jl
This changes the wrapper data structure with an eye towards performance issues in Catlab. When one wraps a model, one looks up whether `impl_type` for all the type constructors has been implemented (this is then *cached*). 
In the future, some keyword (perhaps?) would let you additionally check whether all the *methods* have been implemented, but this tends to be expensive to do indiscriminately.  The edge case where one has implemented all of the type constructors but not all the methods is one we'll have to deal with in the future.
> Change wrapper data structure
